window.MARSZ_CARDS = [
  {
    id: "phone-scroll",
    illustration: "./assets/temp-image.png",
    situation: "W srodku sceny grozy jeden z graczy zaczyna scrollowac telefon i pokazuje memy reszcie stolu.",
    left_label: "Robimy minute przerwy",
    right_label: "Wracamy do sceny",
    left_feedback: "Rozladowujesz napiecie, ale potwor musi teraz drugi raz budowac wejscie.",
    right_feedback: "Telefon znika ze stolu, a klimat wraca z lekkim kaszlnieciem.",
    left_effects: { sanity: -5, engagement: 5 },
    right_effects: { sanity: 5, engagement: -5 },
  },
  {
    id: "fantasy-gun",
    illustration: "./assets/temp-image.png",
    situation: "Gracz w klasycznym fantasy pyta, czy jego bohater moze jednak wyciagnac dwa pistolety spod plaszcza.",
    left_label: "Tak, ale magiczne",
    right_label: "Trzymamy konwencje",
    left_feedback: "Pistolety staja sie runicznymi relikwiami. Klimat chwieje sie, ale nie upada.",
    right_feedback: "Swiat zostaje spojny, a bohater dostaje kusze z charakterem.",
    left_effects: { sanity: -10, engagement: 10 },
    right_effects: { sanity: 5, engagement: -5 },
  },
  {
    id: "last-minute-cancel",
    illustration: "./assets/temp-image.png",
    situation: "Na dwie godziny przed sesja dwoch graczy odwoluje spotkanie, kiedy masz juz wszystko przygotowane.",
    left_label: "Gram dla reszty",
    right_label: "Przekladamy sesje",
    left_feedback: "Wieczor jest uratowany, ale plan kampanii wymaga akrobatyki.",
    right_feedback: "Chronisz sklad druzyny, ale twoje notatki sycza z frustracji.",
    left_effects: { sanity: -10, engagement: 5 },
    right_effects: { sanity: -5, engagement: -10 },
  },
  {
    id: "zero-notes",
    illustration: "./assets/temp-image.png",
    situation: "Gracze wracaja po dwoch tygodniach i nikt nie pamieta, kim byl glowny zloczynca ani po co weszli do ruin.",
    left_label: "Robimy przypomnienie",
    right_label: "Niech sami sobie przypomna",
    left_feedback: "Piec minut streszczenia ratuje sesje i twoje cisnienie.",
    right_feedback: "Zapada niezreczna cisza, a fabula tonie w domyslach.",
    left_effects: { sanity: 5, engagement: 5 },
    right_effects: { sanity: -10, engagement: -10 },
  },
  {
    id: "joke-loop",
    illustration: "./assets/temp-image.png",
    situation: "Jeden z graczy zamienia kazdy opis NPC w zart i stol zaczyna isc bardziej w kabaret niz w przygode.",
    left_label: "Gram z tym humorem",
    right_label: "Przywoluje ton sceny",
    left_feedback: "Sesja zyje, ale powazny baron brzmi teraz jak stand-uper.",
    right_feedback: "Humor zostaje, lecz scena odzyskuje jakas wage.",
    left_effects: { sanity: -5, engagement: 10 },
    right_effects: { sanity: 5, engagement: -5 },
  },
  {
    id: "lore-vacuum",
    illustration: "./assets/temp-image.png",
    situation: "Wprowadzasz starozytna przepowiednie, a gracze reaguja pytaniem, czy w miescie jest sklep z kebabem.",
    left_label: "Improwizuje kebab",
    right_label: "Wracam do przepowiedni",
    left_feedback: "Sklep istnieje i nagle staje sie najwazniejszym miejscem w kampanii.",
    right_feedback: "Czesciowo odzyskujesz uwage, ale klimat nadal trzeba zszywac.",
    left_effects: { sanity: -10, engagement: 10 },
    right_effects: { sanity: 5, engagement: -5 },
  },
  {
    id: "solo-spotlight",
    illustration: "./assets/temp-image.png",
    situation: "Jeden gracz dominuje rozmowe i zanim inni dojda do slowa, ma juz trzy plany, dwa monologi i jeden romans z NPC.",
    left_label: "Niech prowadzi scene",
    right_label: "Pytam innych o ruch",
    left_feedback: "Tempo jest wysokie, ale reszta stolu powoli znika z kadru.",
    right_feedback: "Scena sie wyrownuje i kilku cichszych graczy wraca do gry.",
    left_effects: { sanity: -5, engagement: 5 },
    right_effects: { sanity: 5, engagement: 10 },
  },
  {
    id: "rules-unread",
    illustration: "./assets/temp-image.png",
    situation: "Po raz trzeci tlumaczysz tej samej osobie, jak dziala jej podstawowa umiejetnosc, bo nadal nie przeczytala karty postaci.",
    left_label: "Tlumacze jeszcze raz",
    right_label: "Niech przeczyta teraz",
    left_feedback: "Sesja plynie dalej, ale twoja cierpliwosc traci punkty pancerza.",
    right_feedback: "Tempo siada na chwile, za to nauka wreszcie zostaje z graczem.",
    left_effects: { sanity: -10, engagement: -5 },
    right_effects: { sanity: 5, engagement: 5 },
  },
  {
    id: "mood-break",
    illustration: "./assets/temp-image.png",
    situation: "Po dlugim budowaniu mroku gracz pyta smiertelnie serio, czy smok przyjmuje BLIK-a.",
    left_label: "Tak, i daje rabat",
    right_label: "Smok nie zna bankowosci",
    left_feedback: "Stol wybucha smiechem, a groza idzie na spacer.",
    right_feedback: "Dowcip odbija sie od tarczy klimatu i scena jeszcze sie trzyma.",
    left_effects: { sanity: -5, engagement: 10 },
    right_effects: { sanity: 5, engagement: -5 },
  },
  {
    id: "missing-backstory",
    illustration: "./assets/temp-image.png",
    situation: "Gracz przychodzi bez konceptu postaci i mowi, ze cos wymysli w trakcie pierwszej sceny.",
    left_label: "Tworzymy w locie",
    right_label: "Dajemy szybki szablon",
    left_feedback: "Improwizacja daje wolnosc, ale start sesji staje sie warsztatem awaryjnym.",
    right_feedback: "Bohater rusza szybciej, chociaz mniej po swojemu.",
    left_effects: { sanity: -5, engagement: 5 },
    right_effects: { sanity: 5, engagement: 0 },
  },
  {
    id: "schedule-chaos",
    illustration: "./assets/temp-image.png",
    situation: "Na grupie trwa 40-wiadomosciowa dyskusja o terminie, a finalnie nadal nie wiadomo, kiedy gracie.",
    left_label: "Ustalam staly termin",
    right_label: "Szukamy dalej",
    left_feedback: "Porzadek wraca, choc nie wszyscy klaskaja z radosci.",
    right_feedback: "Elastycznosc brzmi pieknie, dopoki nie zamienia sie w mgla.",
    left_effects: { sanity: 10, engagement: -5 },
    right_effects: { sanity: -10, engagement: -5 },
  },
  {
    id: "genre-drift",
    illustration: "./assets/temp-image.png",
    situation: "Kampania miala byc low fantasy, ale druzyna chce cyber-oka, motocykl i granat dymny jeszcze przed pierwszym locham.",
    left_label: "Mieszam gatunki",
    right_label: "Pilnuje tonu",
    left_feedback: "Powstaje szalona hybryda, ktora moze byc swietna albo bardzo glosna.",
    right_feedback: "Swiat zachowuje charakter, a granice staja sie czytelne.",
    left_effects: { sanity: -10, engagement: 10 },
    right_effects: { sanity: 5, engagement: -5 },
  },
  {
    id: "table-sidequest",
    illustration: "./assets/temp-image.png",
    situation: "Dwie osoby prowadza obok glowna rozmowe o serialach i reszta stolu zaczyna sluchac ich zamiast ciebie.",
    left_label: "Czekam az skoncza",
    right_label: "Zawracam uwage",
    left_feedback: "Konwersacja zyje, ale scena umiera po cichu.",
    right_feedback: "Troche zgrzyta, lecz przygoda odzyskuje pierwszenstwo.",
    left_effects: { sanity: -10, engagement: -10 },
    right_effects: { sanity: 5, engagement: 0 },
  },
  {
    id: "npc-ignore",
    illustration: "./assets/temp-image.png",
    situation: "Przygotowany od tygodnia tajemniczy mentor zaczyna przemowe, a gracze natychmiast pytaja tylko o ceny lin i pochodni.",
    left_label: "Sprzedawca przejmuje scene",
    right_label: "Mentor ucina handel",
    left_feedback: "Mentor przegrywa z ekwipunkiem, ale stol przynajmniej czegos chce.",
    right_feedback: "Watek fabularny wraca na tory z odrobina teatralnej przemocy.",
    left_effects: { sanity: -10, engagement: 5 },
    right_effects: { sanity: 5, engagement: -5 },
  },
  {
    id: "late-player",
    illustration: "./assets/temp-image.png",
    situation: "Sesja miala zaczac sie o 19:00, ale jedna osoba regularnie wpada o 19:35 i wszyscy na nia czekaja.",
    left_label: "Zaczynam bez niej",
    right_label: "Czekamy razem",
    left_feedback: "Szanujesz czas reszty, lecz spoznialski moze wejsc w chaosie.",
    right_feedback: "Nikt nie czuje sie pominity, ale punktualnosc znow przegrywa.",
    left_effects: { sanity: 5, engagement: 5 },
    right_effects: { sanity: -10, engagement: -5 },
  },
  {
    id: "combat-tab-out",
    illustration: "./assets/temp-image.png",
    situation: "Podczas walki online jeden z graczy ewidentnie gra w cos innego i odzywa sie dopiero, gdy przychodzi jego tura.",
    left_label: "Przypominam stawke",
    right_label: "Pomijam po chwili",
    left_feedback: "Masz szanse odzyskac jego uwage bez wojny pasywno-agresywnej.",
    right_feedback: "Tempo rośnie, ale relacja przy stole lekko trzeszczy.",
    left_effects: { sanity: 0, engagement: 5 },
    right_effects: { sanity: 5, engagement: -10 },
  },
  {
    id: "prep-wasted",
    illustration: "./assets/temp-image.png",
    situation: "Przygotowales mapy, glosy NPC i muzyke, a gracze po 15 minutach skrecaja w zupelnie inna strone.",
    left_label: "Ide za nimi",
    right_label: "Podsuwam przygotowany trop",
    left_feedback: "Improwizacja boli, ale stol czuje prawdziwa wolnosc wyboru.",
    right_feedback: "Twoja praca sie przydaje, choc szwy prowadzenia zaczynaja byc widoczne.",
    left_effects: { sanity: -10, engagement: 10 },
    right_effects: { sanity: 5, engagement: -5 },
  },
  {
    id: "grim-joke",
    illustration: "./assets/temp-image.png",
    situation: "W scenie pogrzebu waznego NPC ktos zaczyna robic glupie glosy i cala dramaturgia ucieka przez okno.",
    left_label: "Przerabiam scene na lekka",
    right_label: "Prosze o powage",
    left_feedback: "Ton zmienia sie calkowicie, ale grupa moze poczuc sie swobodniej.",
    right_feedback: "Ryzykujesz lekkie spiecie, za to scena ma szanse cos znaczyc.",
    left_effects: { sanity: -5, engagement: 5 },
    right_effects: { sanity: 5, engagement: 0 },
  },
  {
    id: "loot-obsession",
    illustration: "./assets/temp-image.png",
    situation: "Po kazdej scenie gracze natychmiast pytaja tylko, co wypada z cial, nawet kiedy to dramatyczna rozmowa z krewnym.",
    left_label: "Daje drobny loot",
    right_label: "Trzymam fokus sceny",
    left_feedback: "Nagroda ich cieszy, ale swiat robi sie coraz bardziej automatowy.",
    right_feedback: "Historia wygrywa z tabelka dropu, przynajmniej na chwile.",
    left_effects: { sanity: -5, engagement: 10 },
    right_effects: { sanity: 5, engagement: -5 },
  },
  {
    id: "homework-energy",
    illustration: "./assets/temp-image.png",
    situation: "Dzieci lub zmeczeni dorosli przychodza po ciezkim dniu i widzisz, ze ledwo maja energie na dluga intryge.",
    left_label: "Upraszczam sesje",
    right_label: "Jade z planem",
    left_feedback: "Dostosowujesz tempo do ludzi i ratujesz wieczor.",
    right_feedback: "Masz swoja wymarzona fabule, tylko grupa zostala gdzies z tylu.",
    left_effects: { sanity: 5, engagement: 10 },
    right_effects: { sanity: -10, engagement: -10 },
  },
  {
    id: "missing-recap-reader",
    illustration: "./assets/temp-image.png",
    situation: "Wyslales recap po poprzedniej sesji, ale oczywiscie nikt go nie przeczytal.",
    left_label: "Czytam streszczenie",
    right_label: "Gramy od razu",
    left_feedback: "Masz deja vu, ale przynajmniej wszyscy wiedza, gdzie sa.",
    right_feedback: "Start jest szybki, lecz orientacja druzyny przypomina rzut w ciemno.",
    left_effects: { sanity: -5, engagement: 5 },
    right_effects: { sanity: -10, engagement: -5 },
  },
  {
    id: "sudden-pvp",
    illustration: "./assets/temp-image.png",
    situation: "Z nudow dwoch graczy zaczyna prowokowac PvP, mimo ze kampania miala byc o wspolpracy.",
    left_label: "Pozwalam na starcie",
    right_label: "Stop, wracamy do celu",
    left_feedback: "Emocje rosna natychmiast, ale kampania moze dostac pekniecie na stale.",
    right_feedback: "Gaszenie iskry boli ego, za to chroni druzyne.",
    left_effects: { sanity: -10, engagement: 10 },
    right_effects: { sanity: 5, engagement: -5 },
  },
  {
    id: "session-end-cliffhanger",
    illustration: "./assets/temp-image.png",
    situation: "Musisz konczyc, ale gracze dopiero po godzinie rozproszen wreszcie weszli w klimat i sa przy drzwiach do finalu.",
    left_label: "Jeszcze jedna scena",
    right_label: "Cliffhanger na teraz",
    left_feedback: "Wszyscy sa zadowoleni, tylko jutro bedziesz zombie.",
    right_feedback: "Budujesz apetyt na kolejny raz i ratujesz swoje zasoby.",
    left_effects: { sanity: -10, engagement: 10 },
    right_effects: { sanity: 5, engagement: 5 },
  },
];
