window.MARSZ_CARDS = [
  {
    id: "phone-scroll",
    illustration: "./assets/phone-scroll.jpg",
    situation: "W środku sceny grozy jeden z graczy zaczyna scrollować telefon i pokazuje memy reszcie stołu.",
    left_label: "Robimy minutę przerwy",
    right_label: "Wracamy do sceny",
    left_feedback: "Rozładowujesz napięcie, ale potwór musi teraz drugi raz budować wejście.",
    right_feedback: "Telefon znika ze stołu, a klimat wraca z lekkim kaszlnięciem.",
    left_effects: { sanity: -10, engagement: 10 },
    right_effects: { sanity: 10, engagement: -10 },
  },
  {
    id: "fantasy-gun",
    illustration: "./assets/fantasy-gun.jpg",
    situation: "Gracz w klasycznym fantasy pyta, czy jego bohater może jednak wyciągnąć dwa pistolety spod płaszcza.",
    left_label: "Tak, ale magiczne",
    right_label: "Trzymamy konwencję",
    left_feedback: "Pistolety stają się runicznymi relikwiami. Klimat chwieje się, ale nie upada.",
    right_feedback: "Świat zostaje spójny, a bohater dostaje kuszę z charakterem.",
    left_effects: { sanity: -20, engagement: 20 },
    right_effects: { sanity: 10, engagement: -10 },
  },
  {
    id: "last-minute-cancel",
    illustration: "./assets/last-minute-cancel.jpg",
    situation: "Na dwie godziny przed sesją dwóch graczy odwołuje spotkanie, kiedy masz już wszystko przygotowane.",
    left_label: "Gram dla reszty",
    right_label: "Przekładamy sesję",
    left_feedback: "Wieczór jest uratowany, ale plan kampanii wymaga akrobatyki.",
    right_feedback: "Chronisz skład drużyny, ale twoje notatki syczą z frustracji.",
    left_effects: { sanity: -20, engagement: 10 },
    right_effects: { sanity: -10, engagement: -20 },
  },
  {
    id: "zero-notes",
    illustration: "./assets/zero-notes.jpg",
    situation: "Gracze wracają po dwóch tygodniach i nikt nie pamięta, kim był główny złoczyńca ani po co weszli do ruin.",
    left_label: "Robimy przypomnienie",
    right_label: "Niech sami sobie przypomnią",
    left_feedback: "Pięć minut streszczenia ratuje sesję i twoje ciśnienie.",
    right_feedback: "Zapada niezręczna cisza, a fabuła tonie w domysłach.",
    left_effects: { sanity: 10, engagement: 10 },
    right_effects: { sanity: -20, engagement: -20 },
  },
  {
    id: "joke-loop",
    illustration: "./assets/joke-loop.jpg",
    situation: "Jeden z graczy zamienia każdy opis NPC w żart i stół zaczyna iść bardziej w kabaret niż w przygodę.",
    left_label: "Gram z tym humorem",
    right_label: "Przywołuję ton sceny",
    left_feedback: "Sesja żyje, ale poważny baron brzmi teraz jak stand-uper.",
    right_feedback: "Humor zostaje, lecz scena odzyskuje jakąś wagę.",
    left_effects: { sanity: -10, engagement: 20 },
    right_effects: { sanity: 10, engagement: -10 },
  },
  {
    id: "lore-vacuum",
    illustration: "./assets/lore-vacuum.jpg",
    situation: "Wprowadzasz starożytną przepowiednię, a gracze reagują pytaniem, czy w mieście jest sklep z kebabem.",
    left_label: "Improwizuję kebab",
    right_label: "Wracam do przepowiedni",
    left_feedback: "Sklep istnieje i nagle staje się najważniejszym miejscem w kampanii.",
    right_feedback: "Częściowo odzyskujesz uwagę, ale klimat nadal trzeba zszywać.",
    left_effects: { sanity: -20, engagement: 20 },
    right_effects: { sanity: 10, engagement: -10 },
  },
  {
    id: "solo-spotlight",
    illustration: "./assets/solo-spotlight.jpg",
    situation: "Jeden gracz dominuje rozmowę i zanim inni dojdą do słowa, ma już trzy plany, dwa monologi i jeden romans z NPC.",
    left_label: "Niech prowadzi scenę",
    right_label: "Pytam innych o ruch",
    left_feedback: "Tempo jest wysokie, ale reszta stołu powoli znika z kadru.",
    right_feedback: "Scena się wyrównuje i kilku cichszych graczy wraca do gry.",
    left_effects: { sanity: -10, engagement: 10 },
    right_effects: { sanity: 10, engagement: 20 },
  },
  {
    id: "rules-unread",
    illustration: "./assets/rules-unread.jpg",
    situation: "Po raz trzeci tłumaczysz tej samej osobie, jak działa jej podstawowa umiejętność, bo nadal nie przeczytała karty postaci.",
    left_label: "Tłumaczę jeszcze raz",
    right_label: "Niech przeczyta teraz",
    left_feedback: "Sesja płynie dalej, ale twoja cierpliwość traci punkty pancerza.",
    right_feedback: "Tempo siada na chwilę, za to nauka wreszcie zostaje z graczem.",
    left_effects: { sanity: -20, engagement: -10 },
    right_effects: { sanity: 10, engagement: 10 },
  },
  {
    id: "mood-break",
    illustration: "./assets/mood-break.jpg",
    situation: "Po długim budowaniu mroku gracz pyta śmiertelnie serio, czy smok przyjmuje BLIK-a.",
    left_label: "Tak, i daje rabat",
    right_label: "Smok nie zna bankowości",
    left_feedback: "Stół wybucha śmiechem, a groza idzie na spacer.",
    right_feedback: "Dowcip odbija się od tarczy klimatu i scena jeszcze się trzyma.",
    left_effects: { sanity: -10, engagement: 20 },
    right_effects: { sanity: 10, engagement: -10 },
  },
  {
    id: "missing-backstory",
    illustration: "./assets/missing-backstory.jpg",
    situation: "Gracz przychodzi bez konceptu postaci i mówi, że coś wymyśli w trakcie pierwszej sceny.",
    left_label: "Tworzymy w locie",
    right_label: "Dajemy szybki szablon",
    left_feedback: "Improwizacja daje wolność, ale start sesji staje się warsztatem awaryjnym.",
    right_feedback: "Bohater rusza szybciej, choć mniej po swojemu.",
    left_effects: { sanity: -10, engagement: 10 },
    right_effects: { sanity: 10, engagement: 0 },
  },
  {
    id: "schedule-chaos",
    illustration: "./assets/schedule-chaos.jpg",
    situation: "Na grupie trwa 40-wiadomościowa dyskusja o terminie, a finalnie nadal nie wiadomo, kiedy gracie.",
    left_label: "Ustalam stały termin",
    right_label: "Szukamy dalej",
    left_feedback: "Porządek wraca, choć nie wszyscy klaszczą z radości.",
    right_feedback: "Elastyczność brzmi pięknie, dopóki nie zamienia się w mgłę.",
    left_effects: { sanity: 20, engagement: -10 },
    right_effects: { sanity: -20, engagement: -10 },
  },
  {
    id: "genre-drift",
    illustration: "./assets/genre-drift.jpg",
    situation: "Kampania miała być low fantasy, ale drużyna chce cyber-oka, motocykl i granat dymny jeszcze przed pierwszym lochem.",
    left_label: "Mieszam gatunki",
    right_label: "Pilnuję tonu",
    left_feedback: "Powstaje szalona hybryda, która może być świetna albo bardzo głośna.",
    right_feedback: "Świat zachowuje charakter, a granice stają się czytelne.",
    left_effects: { sanity: -20, engagement: 20 },
    right_effects: { sanity: 10, engagement: -10 },
  },
  {
    id: "table-sidequest",
    illustration: "./assets/table-sidequest.jpg",
    situation: "Dwie osoby prowadzą obok główną rozmowę o serialach i reszta stołu zaczyna słuchać ich zamiast ciebie.",
    left_label: "Czekam aż skończą",
    right_label: "Zawracam uwagę",
    left_feedback: "Konwersacja żyje, ale scena umiera po cichu.",
    right_feedback: "Trochę zgrzyta, lecz przygoda odzyskuje pierwszeństwo.",
    left_effects: { sanity: -20, engagement: -20 },
    right_effects: { sanity: 10, engagement: 0 },
  },
  {
    id: "npc-ignore",
    illustration: "./assets/npc-ignore.jpg",
    situation: "Przygotowany od tygodnia tajemniczy mentor zaczyna przemowę, a gracze natychmiast pytają tylko o ceny lin i pochodni.",
    left_label: "Sprzedawca przejmuje scenę",
    right_label: "Mentor ucina handel",
    left_feedback: "Mentor przegrywa z ekwipunkiem, ale stół przynajmniej czegoś chce.",
    right_feedback: "Wątek fabularny wraca na tory z odrobiną teatralnej przemocy.",
    left_effects: { sanity: -20, engagement: 10 },
    right_effects: { sanity: 10, engagement: -10 },
  },
  {
    id: "late-player",
    illustration: "./assets/late-player.jpg",
    situation: "Sesja miała zacząć się o 19:00, ale jedna osoba regularnie wpada o 19:35 i wszyscy na nią czekają.",
    left_label: "Zaczynam bez niej",
    right_label: "Czekamy razem",
    left_feedback: "Szanujesz czas reszty, lecz spóźnialski może wejść w chaosie.",
    right_feedback: "Nikt nie czuje się pominięty, ale punktualność znów przegrywa.",
    left_effects: { sanity: 10, engagement: 10 },
    right_effects: { sanity: -20, engagement: -10 },
  },
  {
    id: "combat-tab-out",
    illustration: "./assets/combat-tab-out.jpg",
    situation: "Podczas walki online jeden z graczy ewidentnie gra w coś innego i odzywa się dopiero, gdy przychodzi jego tura.",
    left_label: "Przypominam stawkę",
    right_label: "Pomijam po chwili",
    left_feedback: "Masz szansę odzyskać jego uwagę bez wojny pasywno-agresywnej.",
    right_feedback: "Tempo rośnie, ale relacja przy stole lekko trzeszczy.",
    left_effects: { sanity: 0, engagement: 10 },
    right_effects: { sanity: 10, engagement: -20 },
  },
  {
    id: "prep-wasted",
    illustration: "./assets/prep-wasted.jpg",
    situation: "Przygotowałeś mapy, głosy NPC i muzykę, a gracze po 15 minutach skręcają w zupełnie inną stronę.",
    left_label: "Idę za nimi",
    right_label: "Podsuwam przygotowany trop",
    left_feedback: "Improwizacja boli, ale stół czuje prawdziwą wolność wyboru.",
    right_feedback: "Twoja praca się przydaje, choć szwy prowadzenia zaczynają być widoczne.",
    left_effects: { sanity: -20, engagement: 20 },
    right_effects: { sanity: 10, engagement: -10 },
  },
  {
    id: "grim-joke",
    illustration: "./assets/grim-joke.jpg",
    situation: "W scenie pogrzebu ważnego NPC ktoś zaczyna robić głupie głosy i cała dramaturgia ucieka przez okno.",
    left_label: "Przerabiam scenę na lekką",
    right_label: "Proszę o powagę",
    left_feedback: "Ton zmienia się całkowicie, ale grupa może poczuć się swobodniej.",
    right_feedback: "Ryzykujesz lekkie spięcie, za to scena ma szansę coś znaczyć.",
    left_effects: { sanity: -10, engagement: 10 },
    right_effects: { sanity: 10, engagement: 0 },
  },
  {
    id: "loot-obsession",
    illustration: "./assets/loot-obsession.jpg",
    situation: "Po każdej scenie gracze natychmiast pytają tylko, co wypada z ciał, nawet kiedy to dramatyczna rozmowa z krewnym.",
    left_label: "Daję drobny loot",
    right_label: "Trzymam fokus sceny",
    left_feedback: "Nagroda ich cieszy, ale świat robi się coraz bardziej automatowy.",
    right_feedback: "Historia wygrywa z tabelką dropu, przynajmniej na chwilę.",
    left_effects: { sanity: -10, engagement: 20 },
    right_effects: { sanity: 10, engagement: -10 },
  },
  {
    id: "homework-energy",
    illustration: "./assets/homework-energy.jpg",
    situation: "Dzieci lub zmęczeni dorośli przychodzą po ciężkim dniu i widzisz, że ledwo mają energię na długą intrygę.",
    left_label: "Upraszczam sesję",
    right_label: "Jadę z planem",
    left_feedback: "Dostosowujesz tempo do ludzi i ratujesz wieczór.",
    right_feedback: "Masz swoją wymarzoną fabułę, tylko grupa została gdzieś z tyłu.",
    left_effects: { sanity: 10, engagement: 20 },
    right_effects: { sanity: -20, engagement: -20 },
  },
  {
    id: "missing-recap-reader",
    illustration: "./assets/missing-recap-reader.jpg",
    situation: "Wysłałeś recap po poprzedniej sesji, ale oczywiście nikt go nie przeczytał.",
    left_label: "Czytam streszczenie",
    right_label: "Gramy od razu",
    left_feedback: "Masz déjà vu, ale przynajmniej wszyscy wiedzą, gdzie są.",
    right_feedback: "Start jest szybki, lecz orientacja drużyny przypomina rzut w ciemno.",
    left_effects: { sanity: -10, engagement: 10 },
    right_effects: { sanity: -20, engagement: -10 },
  },
  {
    id: "sudden-pvp",
    illustration: "./assets/sudden-pvp.jpg",
    situation: "Z nudów dwóch graczy zaczyna prowokować PvP, mimo że kampania miała być o współpracy.",
    left_label: "Pozwalam na starcie",
    right_label: "Stop, wracamy do celu",
    left_feedback: "Emocje rosną natychmiast, ale kampania może dostać pęknięcie na stałe.",
    right_feedback: "Gaszenie iskry boli ego, za to chroni drużynę.",
    left_effects: { sanity: -20, engagement: 20 },
    right_effects: { sanity: 10, engagement: -10 },
  },
  {
    id: "session-end-cliffhanger",
    illustration: "./assets/session-end-cliffhanger.jpg",
    situation: "Musisz kończyć, ale gracze dopiero po godzinie rozproszeń wreszcie weszli w klimat i są przy drzwiach do finału.",
    left_label: "Jeszcze jedna scena",
    right_label: "Cliffhanger na teraz",
    left_feedback: "Wszyscy są zadowoleni, tylko jutro będziesz zombie.",
    right_feedback: "Budujesz apetyt na kolejny raz i ratujesz swoje zasoby.",
    left_effects: { sanity: -20, engagement: 20 },
    right_effects: { sanity: 10, engagement: 10 },
  },
];
