// js/tables.js
// Dane wygenerowane z Lonely Patrons/Tables/ (EN) i Tables/PL/ (PL)
var TABLES = {};

TABLES.season = {
  label: { en: "1D4 — SEASON", pl: "1D4 — PORA ROKU" },
  type: "d4",
  en: [null, "Winter", "Autumn", "Spring", "Summer"],
  pl: [null, "Zima", "Jesień", "Wiosna", "Lato"]
};

TABLES.region = {
  label: { en: "D66 — NATURE OF THE REGION", pl: "D66 — NATURA REGIONU" },
  type: "d66",
  en: {
    11: "forest",
    12: "mountain",
    13: "cave / dungeon",
    14: "abandoned hamlet",
    15: "meadow",
    16: "wasteland",
    21: "chaparral",
    22: "pasture",
    23: "delta / marsh",
    24: "cove / beach",
    25: "crop fields",
    26: "ruins",
    31: "gorge / canyon",
    32: "valley",
    33: "mountain peak",
    34: "sparse forest",
    35: "jungle / rain forest",
    36: "abandoned village",
    41: "river / stream",
    42: "desert",
    43: "tundra / steppe",
    44: "mangrove",
    45: "mountain bay",
    46: "cliffs",
    51: "waterfall",
    52: "underground / tunnel",
    53: "swamp",
    54: "hills",
    55: "plain / plateau",
    56: "savanna",
    61: "nature reserve / hot springs",
    62: "volcanic zone",
    63: "taiga",
    64: "floating island",
    65: "archipelago",
    66: "town / gardens"
  },
  pl: {
    11: "las",
    12: "góra",
    13: "jaskinia / loch",
    14: "opuszczona osada",
    15: "łąka",
    16: "pustkowie",
    21: "zarośla śródziemnomorskie",
    22: "pastwisko",
    23: "delta / mokradła",
    24: "zatoczka / plaża",
    25: "pola uprawne",
    26: "ruiny",
    31: "wąwóz / kanion",
    32: "dolina",
    33: "górski szczyt",
    34: "rzadki las",
    35: "dżungla / las deszczowy",
    36: "opuszczona wioska",
    41: "rzeka / strumień",
    42: "pustynia",
    43: "tundra / step",
    44: "namorzyny",
    45: "górska zatoka",
    46: "klify",
    51: "wodospad",
    52: "podziemia / tunel",
    53: "bagno",
    54: "wzgórza",
    55: "równina / płaskowyż",
    56: "sawanna",
    61: "rezerwat przyrody / gorące źródła",
    62: "strefa wulkaniczna",
    63: "tajga",
    64: "pływająca wyspa",
    65: "archipelag",
    66: "miasteczko / ogrody"
  }
};

TABLES.terrain = {
  label: { en: "1D8 — PREDOMINANT TERRAIN", pl: "1D8 — DOMINUJĄCY TEREN" },
  type: "d8",
  en: [null, "sand", "grass", "plants / bushes", "mud / ash", "gravel / rocks", "dirt", "snow", "leaf litter"],
  pl: [null, "piasek", "trawa", "rośliny / krzewy", "błoto / popiół", "żwir / skały", "ziemia", "śnieg", "ściółka"]
};

TABLES.weather = {
  label: { en: "1D12 — WEATHER", pl: "1D12 — POGODA" },
  type: "d12",
  en: [null, "sunny", "very hot", "cloudy", "intermittent rain", "steady rain", "thunderstorms", "snowfall", "fog", "strong winds", "cold", "very cold", "pleasant day"],
  pl: [null, "słonecznie", "bardzo gorąco", "pochmurno", "przelotny deszcz", "stały deszcz", "burze", "opady śniegu", "mgła", "silne wiatry", "zimno", "bardzo zimno", "przyjemny dzień"]
};

TABLES.patronHouse = {
  label: { en: "1D20 — PATRON'S HOUSE", pl: "1D20 — DOM PATRONA" },
  type: "d20",
  en: [null, "camp", "dilapidated house", "cave house", "cabin", "tower", "mansion", "boat", "tent", "shop / business", "inn / tavern", "castle", "tree house", "temple", "renovated house", "carriage", "spaceship", "humble home", "pagoda / lighthouse", "cavern", "farm / library"],
  pl: [null, "obóz", "zrujnowany dom", "dom w jaskini", "chatka", "wieża", "rezydencja", "łódź", "namiot", "sklep / interes", "zajazd / tawerna", "zamek", "domek na drzewie", "świątynia", "odnowiony dom", "powóz", "statek kosmiczny", "skromny dom", "pagoda / latarnia morska", "grota", "farma / biblioteka"]
};

TABLES.regionKnownFor = {
  label: { en: "1D100 — REGION KNOWN FOR...", pl: "1D100 — Z CZEGO SŁYNIE REGION..." },
  type: "d100",
  en: [null, "treasures", "giants", "earthquakes", "unstable climate", "curious ghosts", "fascinating architecture", "majestic animals", "beauty", "legends", "mineral veins", "mysteries of past crimes", "paranormal events", "abandonment", "time almost stopped", "rare animals", "enormous nature", "voices from another time", "buried ships", "forgotten technology", "evocative colors", "intense feelings", "mental calm", "past wars", "little animals", "magical objects", "trade route", "robberies", "delicious mushrooms", "big library", "walls", "vehicles", "new beings", "starry nights", "challenging roads", "lack of resources", "exotic plants", "insect plague", "spore invasion", "religious apparitions", "too much tourism", "ultra-famous monument", "origin of life", "nature burned", "very far away", "very industrial", "wizard towers", "diverse cultures", "diversity", "entry forbidden", "hallucinations", "premonitory dreams", "very fertile land", "helpful monsters", "magic pools", "hidden dragon", "cave paintings", "grants energy", "humor and laughter", "brimming with magic", "low gravity", "bohemianism and madness", "laboratories and observatories", "high modernity", "hidden ultravillain", "fascinating symbols", "all gray", "pastel color", "the great temple", "witches' guild", "aphrodisiac halo", "full of adventurers", "dinosaurs", "falling meteorites", "spectral aspect", "snow and frostbite", "the great yellow lake", "niches and tombs", "talking fruits", "wise trees", "interesting barters", "spiritual beings", "pure labyrinth", "a god lives here", "altruistic guild", "repressive guardians", "gastronomic culture", "performances everywhere", "general clumsiness", "love is in the air", "crazy inventions", "gigantic ruins", "market of extravaganzas", "holograms of the past", "impossible portals", "all very normal", null, null, null, null, null],
  pl: [null, "skarby", "olbrzymy", "trzęsienia ziemi", "niestabilny klimat", "osobliwe duchy", "fascynująca architektura", "majestatyczne zwierzęta", "piękno", "legendy", "żyły minerałów", "tajemnice dawnych zbrodni", "zjawiska paranormalne", "opuszczenie", "czas niemal się zatrzymał", "rzadkie zwierzęta", "ogromna natura", "głosy z innej epoki", "zakopane statki", "zapomniana technologia", "nastrojowe kolory", "intensywne uczucia", "spokój umysłu", "dawne wojny", "małe zwierzęta", "magiczne przedmioty", "szlak handlowy", "rabunki", "pyszne grzyby", "wielka biblioteka", "mury", "pojazdy", "nowe istoty", "gwiaździste noce", "wymagające drogi", "brak zasobów", "egzotyczne rośliny", "plaga owadów", "inwazja zarodników", "religijne objawienia", "zbyt duża turystyka", "ultraznany pomnik", "początek życia", "spalona natura", "bardzo daleko stąd", "silnie uprzemysłowiony", "wieże czarodziejów", "różnorodne kultury", "różnorodność", "wstęp wzbroniony", "halucynacje", "prorocze sny", "bardzo żyzna ziemia", "pomocne potwory", "magiczne sadzawki", "ukryty smok", "malowidła jaskiniowe", "daje energię", "humor i śmiech", "przepełniony magią", "niska grawitacja", "bohema i szaleństwo", "laboratoria i obserwatoria", "wysoka nowoczesność", "ukryty arcyłotr", "fascynujące symbole", "wszystko szare", "pastelowy kolor", "wielka świątynia", "gildia wiedźm", "zmysłowa aura", "pełno poszukiwaczy przygód", "dinozaury", "spadające meteoryty", "widmowy wygląd", "śnieg i odmrożenia", "wielkie żółte jezioro", "nisze i grobowce", "mówiące owoce", "mądre drzewa", "interesujące wymiany barterowe", "istoty duchowe", "czysty labirynt", "mieszka tu bóg", "altruistyczna gildia", "opresyjni strażnicy", "kultura gastronomiczna", "przedstawienia wszędzie", "ogólna niezdarność", "miłość unosi się w powietrzu", "szalone wynalazki", "gigantyczne ruiny", "targ ekstrawagancji", "hologramy przeszłości", "niemożliwe portale", "wszystko całkiem normalne", null, null, null, null, null]
};

TABLES.appearance = {
  label: { en: "1D4 — APPEARANCE", pl: "1D4 — WYGLĄD" },
  type: "d4",
  en: [null, "young", "adult", "mature", "gray-haired"],
  pl: [null, "młody", "dorosły", "dojrzały", "siwowłosy"]
};

TABLES.personality = {
  label: { en: "D66 — PERSONALITY", pl: "D66 — OSOBOWOŚĆ" },
  type: "d66",
  en: {
    11: "formal",
    12: "hooligan",
    13: "careless",
    14: "curious",
    15: "romantic",
    16: "close",
    21: "stubborn",
    22: "interesting",
    23: "vehement",
    24: "unsociable",
    25: "inspiring",
    26: "manipulative",
    31: "submissive",
    32: "pessimistic",
    33: "dreamy",
    34: "funny / joking",
    35: "intelligent",
    36: "ambitious",
    41: "clumsy",
    42: "brave",
    43: "calm",
    44: "overwhelming",
    45: "cynical / sarcastic",
    46: "passionate",
    51: "optimistic",
    52: "mystical / mysterious",
    53: "talkative",
    54: "thoughtful",
    55: "rambling",
    56: "fearful",
    61: "shy",
    62: "gloomy",
    63: "dramatic",
    64: "helpful",
    65: "know-it-all / wise",
    66: "pragmatic / traditional"
  },
  pl: {
    11: "formalny",
    12: "chuligański",
    13: "beztroski",
    14: "ciekawski",
    15: "romantyczny",
    16: "bliski",
    21: "uparty",
    22: "interesujący",
    23: "gwałtowny",
    24: "nietowarzyski",
    25: "inspirujący",
    26: "manipulacyjny",
    31: "uległy",
    32: "pesymistyczny",
    33: "marzycielski",
    34: "zabawny / żartobliwy",
    35: "inteligentny",
    36: "ambitny",
    41: "niezdarny",
    42: "odważny",
    43: "spokojny",
    44: "przytłaczający",
    45: "cyniczny / sarkastyczny",
    46: "pełen pasji",
    51: "optymistyczny",
    52: "mistyczny / tajemniczy",
    53: "gadatliwy",
    54: "refleksyjny",
    55: "rozwlekły",
    56: "lękliwy",
    61: "nieśmiały",
    62: "ponury",
    63: "dramatyczny",
    64: "pomocny",
    65: "mądrala / mądry",
    66: "pragmatyczny / tradycyjny"
  }
};

TABLES.nameInitials = {
  label: { en: "1D8 — NAME", pl: "1D8 — IMIĘ" },
  type: "d8",
  en: [null, "ABCD", "EFG", "HIJK", "LMN", "OPQ", "RST", "UVW", "XYZ"],
  pl: [null, "ABCD", "EFG", "HIJK", "LMN", "OPQ", "RST", "UVW", "XYZ"]
};

TABLES.ancestry = {
  label: { en: "1D12 — ANCESTRY", pl: "1D12 — POCHODZENIE" },
  type: "d12",
  en: [null, "human", "human", "human", "subtle animal traits", "elf", "dwarf / orc", "half-giant", "automaton / robot", "monster", "ghost / spectre", "gnome / goblin", "demi-god / magical being"],
  pl: [null, "człowiek", "człowiek", "człowiek", "subtelne cechy zwierzęce", "elf", "krasnolud / ork", "półolbrzym", "automat / robot", "potwór", "duch / widmo", "gnom / goblin", "półbóg / magiczna istota"]
};

TABLES.talent = {
  label: { en: "1D20 — TALENT", pl: "1D20 — TALENT" },
  type: "d20",
  en: [null, "medicine / foraging / repairing", "hunting / fishing / veterinary", "magic / religion / stealing", "meditation / politics / teaching", "mechanics / crafting / carpentry", "witchcraft / seer / cartography", "building / knitting / cooking", "potions / herbs / drinks", "languages / sailing / driving", "business / comedy / civil servant", "manage / history / paranormal", "police / law / travel", "free soul / music / dance", "performance / psychology / massage", "journalism / cleaning / restoring", "antiques / manager / spy", "sport / adventure / books", "treasure hunter / cakes / painting / forging", "technology / detective / storing", "reselling / courier / farming / games"],
  pl: [null, "medycyna / zbieractwo / naprawy", "łowiectwo / rybołówstwo / weterynaria", "magia / religia / kradzież", "medytacja / polityka / nauczanie", "mechanika / rzemiosło / stolarstwo", "czarownictwo / jasnowidzenie / kartografia", "budowanie / robienie na drutach / gotowanie", "mikstury / zioła / napoje", "języki / żeglowanie / prowadzenie pojazdów", "biznes / komedia / urzędnik", "zarządzanie / historia / zjawiska paranormalne", "policja / prawo / podróże", "wolny duch / muzyka / taniec", "występy / psychologia / masaż", "dziennikarstwo / sprzątanie / renowacja", "antyki / menedżer / szpieg", "sport / przygoda / książki", "łowca skarbów / ciasta / malowanie / fałszerstwo", "technologia / detektyw / magazynowanie", "odsprzedaż / kurierka / rolnictwo / gry"]
};

TABLES.ttrpgThemes = {
  label: { en: "1D100 — TTRPG THEMES", pl: "1D100 — MOTYWY TTRPG" },
  type: "d100",
  en: [null, "dark fantasy", "medieval", "sci-fi / technology", "Jane Austen", "romance", "robbery / thieves", "farm", "epic fantasy", "sport", "tribes", "exploration", "archeology", "space", "investigation", "Lovecraft - cosmic horror", "travel / races", "coming-of-age", "cartography", "photography / design", "queer", "vampires", "superheroes", "worldbuilding", "future / past", "dinosaurs", "cats", "animals", "retro", "vikings", "mechs", "cozy", "store or business management", "ruins", "desert", "road trip", "dungeons", "samurai / ninjas", "monsters", "anime / magical girls", "soap opera / fashion", "citybuilder", "nature", "politics", "revenge", "friendship", "courier", "post-apocalypse", "life simulator / slice of life", "fight / duels", "play to lose", "collect", "survival", "fishing / hunting", "construction", "adventure", "social", "be an object", "princesses", "evil versus good", "comedy", "mental illness", "robots", "aliens", "artists / music", "magic", "witchcraft", "collaborative", "martial arts", "be a goblin", "noir", "sailing", "police", "pirates", "wars", "drama", "treasures", "conversations", "vulnerability", "grotesque / absurd", "gangs", "politically incorrect", "time travel", "psychological terror", "cooking", "dreamlike / surrealism", "mythology", "epistolary", "costumbrismo", "cyberpunk", "steampunk", "horror folk", "western", "mafia / espionage", "solarpunk", "simulated reality", "alchemy / potions / herbs", "dystopia", "be a god", "isekai", "high school / university"],
  pl: [null, "mroczne fantasy", "średniowiecze", "science fiction / technologia", "Jane Austen", "romans", "napad / złodzieje", "farma", "epickie fantasy", "sport", "plemiona", "eksploracja", "archeologia", "kosmos", "śledztwo", "Lovecraft - kosmiczny horror", "podróż / wyścigi", "dojrzewanie", "kartografia", "fotografia / projektowanie", "queer", "wampiry", "superbohaterowie", "worldbuilding", "przyszłość / przeszłość", "dinozaury", "koty", "zwierzęta", "retro", "wikingowie", "mechy", "przytulne", "zarządzanie sklepem lub biznesem", "ruiny", "pustynia", "road trip", "lochy", "samuraje / ninja", "potwory", "anime / magiczne dziewczyny", "opera mydlana / moda", "budowanie miasta", "natura", "polityka", "zemsta", "przyjaźń", "kurier", "postapokalipsa", "symulator życia / slice of life", "walka / pojedynki", "gra o przegrywaniu", "kolekcjonowanie", "przetrwanie", "rybołówstwo / łowiectwo", "budowa", "przygoda", "relacje społeczne", "bycie przedmiotem", "księżniczki", "zło kontra dobro", "komedia", "choroba psychiczna", "roboty", "kosmici", "artyści / muzyka", "magia", "czarownictwo", "współtworzenie", "sztuki walki", "bycie goblinem", "noir", "żeglowanie", "policja", "piraci", "wojny", "dramat", "skarby", "rozmowy", "wrażliwość", "groteska / absurd", "gangi", "politycznie niepoprawne", "podróże w czasie", "terror psychologiczny", "gotowanie", "oniryczność / surrealizm", "mitologia", "epistolarne", "kostumbryzm", "cyberpunk", "steampunk", "folk horror", "western", "mafia / szpiegostwo", "solarpunk", "symulowana rzeczywistość", "alchemia / mikstury / zioła", "dystopia", "bycie bogiem", "isekai", "liceum / uniwersytet"]
};

TABLES.system = {
  label: { en: "SYSTEM", pl: "SYSTEM" },
  type: "d20",
  en: [null, "PBtA", "D20", "2D6", "Rules-light", "Freeform", "FKR", "Jenga tower", "Tarot", "Poker cards", "D100 / BRP", "Fate", "OSR", "Crunchy", "Narrative", "Belonging Outside Belonging", "1D6", "1D6 and Poker cards", "Journaling", "All the dice", "Another system or your own custom-made one (35 WPs)"],
  pl: [null, "PBtA", "D20", "2D6", "lekkie zasady", "freeform", "FKR", "wieża z Jengi", "Tarot", "karty do pokera", "D100 / BRP", "Fate", "OSR", "ciężkie mechanicznie", "narracyjny", "Belonging Outside Belonging", "1D6", "1D6 i karty do pokera", "journaling", "wszystkie kości", "inny system albo własny autorski (35 WP)"]
};

TABLES.activities = {
  label: { en: "AFTERNOON — ACTIVITIES", pl: "POPOŁUDNIE — AKTYWNOŚCI" },
  type: "d100",
  en: [null, "jogging", "meditate", "fishing", "hunting", "book club", "catch bugs", "hiking", "drink tasting", "cook", "take a bath", "role-playing", "play cards / dice", "clean", "repair", "look for fruit", "tell jokes", "listen to music", "play music / sing", "pick herbs", "climb", "go on adventures", "look for treasure", "race", "pet animals", "create objects", "take a nap", "carpentry", "kendo", "archery", "create jewelry", "knit", "dance", "have a drink", "have a snack", "review photos", "create a spell", "create a potion", "visit a monument", "sunset", "pick mushrooms", "sport - ball", "makeup", "fashion", "fight monsters", "invent something", "watch a movie", "telescope", "look for ghosts", "dig a hole", "explore a cave", "take care of the garden", "take care of nature", "cure an animal", "listen to nature", "acrobatics", "bicycle", "create a weapon", "pick flowers", "poetry", "paint", "make a cake", "redecorate", "pick up trash", "lift weights", "break things", "smells", "hugs / photographs", "coffee / dressing up", "act - play", "cartography", "calligraphy", "video games", "learn a language", "look for gemstones", "jump into the water", "rollerskate / skateboard", "sail", "take care of a farm", "study a topic", "watch a play", "watch a comedian", "predict the future", "count and sort resources", "build furniture", "carry packages", "help the disadvantaged", "write letters", "yoga / pilates", "solve a mystery", "paint a house", "crafts", "walk", "visit neighbor", "daydreaming", "painting figurines", "martial arts", "sunbathing", "swimming / diving", "[patron talent]", "[about the landscape]"],
  pl: [null, "jogging", "medytacja", "wędkowanie", "polowanie", "klub książki", "łapanie robaków", "wędrówka", "degustacja napojów", "gotowanie", "kąpiel", "odgrywanie ról", "granie w karty / kości", "sprzątanie", "naprawianie", "szukanie owoców", "opowiadanie żartów", "słuchanie muzyki", "granie muzyki / śpiew", "zbieranie ziół", "wspinaczka", "wyprawy przygodowe", "szukanie skarbów", "wyścigi", "głaskanie zwierząt", "tworzenie przedmiotów", "drzemka", "stolarstwo", "kendo", "łucznictwo", "tworzenie biżuterii", "robienie na drutach", "taniec", "wspólne picie", "przekąska", "przeglądanie zdjęć", "tworzenie zaklęcia", "tworzenie mikstury", "odwiedzanie pomnika", "oglądanie zachodu słońca", "zbieranie grzybów", "sport - piłka", "makijaż", "moda", "walka z potworami", "wymyślanie czegoś", "oglądanie filmu", "obserwacje przez teleskop", "szukanie duchów", "kopanie dołu", "eksploracja jaskini", "dbanie o ogród", "dbanie o naturę", "leczenie zwierzęcia", "słuchanie natury", "akrobatyka", "jazda na rowerze", "tworzenie broni", "zbieranie kwiatów", "poezja", "malowanie", "pieczenie ciasta", "przemeblowanie", "zbieranie śmieci", "podnoszenie ciężarów", "psucie rzeczy", "zapachy", "uściski / fotografie", "kawa / strojenie się", "granie w sztuce", "kartografia", "kaligrafia", "gry wideo", "nauka języka", "szukanie kamieni szlachetnych", "skok do wody", "jazda na rolkach / deskorolce", "żeglowanie", "dbanie o farmę", "studiowanie tematu", "oglądanie przedstawienia", "oglądanie komika", "przepowiadanie przyszłości", "liczenie i sortowanie zasobów", "budowanie mebli", "noszenie paczek", "pomoc pokrzywdzonym", "pisanie listów", "joga / pilates", "rozwiązywanie tajemnicy", "malowanie domu", "rękodzieło", "spacer", "odwiedziny u sąsiada", "bujanie w obłokach", "malowanie figurek", "sztuki walki", "opalanie", "pływanie / nurkowanie", "[talent patrona]", "[o krajobrazie]"]
};

TABLES.enjoyment = {
  label: { en: "YOUR ENJOYMENT", pl: "TWOJA PRZYJEMNOŚĆ" },
  type: "d12",
  en: [null, "I was bored this time...", "I learned something interesting.", "Lots of jokes and laughter.", "There was a really cool vibe.", "This isn't my thing...", "I kept looking at my watch...", "It was a fun time.", "We got to know each other better.", "It was quite inspiring.", "I felt like I didn't fit in...", "I got hurt during the activity...", "They got hurt during the activity..."],
  pl: [null, "Tym razem było nudno...", "Dało się nauczyć czegoś ciekawego.", "Mnóstwo żartów i śmiechu.", "Panował naprawdę fajny klimat.", "To nie moja bajka...", "Ciągłe zerkanie na zegarek...", "To był przyjemnie spędzony czas.", "Udało się lepiej poznać.", "To było całkiem inspirujące.", "Było poczucie niedopasowania...", "Ktoś zranił się podczas tej aktywności...", "Patron zranił się podczas tej aktywności..."]
};

TABLES.tone = {
  label: { en: "TONE", pl: "TON" },
  type: "d6",
  en: [null, "Affects the patron", "Humorous", "Rumor / legend", "Constructive criticism", "Anecdote", "A debate is generated"],
  pl: [null, "Porusza patrona", "Humorystyczny", "Plotka / legenda", "Konstruktywna krytyka", "Anegdota", "Rodzi się debata"]
};

TABLES.topic = {
  label: { en: "TOPIC", pl: "TEMAT" },
  type: "d100",
  en: [null, "family", "friendship", "love", "talent", "freedom", "dreams", "monsters", "work", "growth", "shortage", "magical beings", "technology", "tradition", "modernity", "battle", "magic", "adventure", "potential", "decadence", "lie", "innovation", "art", "animals", "herbs / plants", "creativity", "invention", "descendants", "error", "progress", "secret", "nature", "trap", "virtue", "defect", "teaching", "games", "accident", "miracle", "explore", "cure", "mysticism", "stories / books", "altruism", "tourism", "contradictory", "ambition", "treasures", "party fun", "health", "laws / manipulate", "resources", "amusement", "power", "conspiracy", "emotion", "everyday", "fame", "stars", "experience", "cooking", "mischief", "philosophy", "beautiful things", "discovery", "artifact", "fashion", "injustice", "sacrifice", "peace", "kingdoms", "legend", "rumor", "gossip", "obsession", "belief", "culture", "humor", "catastrophe", "past", "future", "present", "shopping / whims", "mystery", "politics", "disadvantaged", "hero", "villain", "exercise", "illness", "whim", "loyalty", "betrayal", "human rights", "regrets", "old age", "wisdom", "reinventing yourself", "[about your character]", "[about the landscape]", "[about the talent of the patron]"],
  pl: [null, "rodzina", "przyjaźń", "miłość", "talent", "wolność", "sny", "potwory", "praca", "rozwój", "braki", "magiczne istoty", "technologia", "tradycja", "nowoczesność", "bitwa", "magia", "przygoda", "potencjał", "dekadencja", "kłamstwo", "innowacja", "sztuka", "zwierzęta", "zioła / rośliny", "kreatywność", "wynalazek", "potomkowie", "błąd", "postęp", "sekret", "natura", "pułapka", "cnota", "wada", "nauczanie", "gry", "wypadek", "cud", "eksploracja", "leczenie", "mistycyzm", "historie / książki", "altruizm", "turystyka", "sprzeczności", "ambicja", "skarby", "imprezowa zabawa", "zdrowie", "prawa / manipulacja", "zasoby", "rozrywka", "władza", "spisek", "emocja", "codzienność", "sława", "gwiazdy", "doświadczenie", "gotowanie", "psoty", "filozofia", "piękne rzeczy", "odkrycie", "artefakt", "moda", "niesprawiedliwość", "poświęcenie", "pokój", "królestwa", "legenda", "plotka", "obmowa", "obsesja", "przekonanie", "kultura", "humor", "katastrofa", "przeszłość", "przyszłość", "teraźniejszość", "zakupy / zachcianki", "tajemnica", "polityka", "pokrzywdzeni", "bohater", "złoczyńca", "ćwiczenia", "choroba", "kaprys", "lojalność", "zdrada", "prawa człowieka", "żale", "starość", "mądrość", "wymyślanie siebie na nowo", "[o twojej postaci]", "[o krajobrazie]", "[o talencie patrona]"]
};

TABLES.delivery = {
  label: { en: "DELIVERY", pl: "WRĘCZENIE" },
  type: "2d6",
  en: [
    { min: 2, max: 4, text: "It doesn't fully convince them, but they keep it..." },
    { min: 5, max: 7, text: "They appreciate it and say they'll play it soon." },
    { min: 8, max: 9, text: "They find it interesting and are eager to try it." },
    { min: 10, max: 10, text: "Their smile reflects great enthusiasm." },
    { min: 11, max: 11, text: "It touches their heart, and they thank you profusely." },
    { min: 12, max: 12, text: "They are moved to tears and give you a heartfelt hug. They can't wait to play it." }
  ],
  pl: [
    { min: 2, max: 4, text: "Nie do końca ich to przekonuje, ale i tak to zachowują..." },
    { min: 5, max: 7, text: "Doceniają to i mówią, że wkrótce zagrają." },
    { min: 8, max: 9, text: "Uznają to za interesujące i chcą szybko spróbować." },
    { min: 10, max: 10, text: "Ich uśmiech wyraża wielki entuzjazm." },
    { min: 11, max: 11, text: "To porusza ich serce i wylewnie ci dziękują." },
    { min: 12, max: 12, text: "Wzruszają się do łez i przytulają cię z całego serca. Nie mogą się doczekać, by zagrać." }
  ]
};

TABLES.whatTheyLove = {
  label: { en: "WHAT THEY LOVE MOST ABOUT THE GAME", pl: "CO NAJBARDZIEJ KOCHAJĄ W GRZE" },
  type: "d6",
  en: [null, "Texts", "Design", "Illustration", "Freedom", "Rules", "Themes"],
  pl: [null, "Teksty", "Projekt", "Ilustracja", "Wolność", "Zasady", "Motywy"]
};

TABLES.proposal = {
  label: { en: "PROPOSAL", pl: "PROPOZYCJA" },
  type: "2d6",
  en: [
    { min: 2, max: 7, text: "They make excuses or don't find it appropriate." },
    { min: 8, max: 10, text: "They accept if the interaction or proposal seems reasonable." },
    { min: 11, max: 12, text: "They accept without reservation and with pleasure." }
  ],
  pl: [
    { min: 2, max: 7, text: "Szukają wymówek albo nie uważają tego za stosowne." },
    { min: 8, max: 10, text: "Zgadzają się, jeśli interakcja lub propozycja wydaje się rozsądna." },
    { min: 11, max: 12, text: "Zgadzają się bez wahania i z przyjemnością." }
  ]
};

TABLES.importantEvent = {
  label: { en: "IMPORTANT EVENT", pl: "WAŻNE WYDARZENIE" },
  type: "age",
  en: {
    17: "Gets their heart broken",
    18: "Studies fine arts",
    19: "Gains a pet",
    20: "Learns a new talent",
    21: "Has a great adventure",
    22: "Works other jobs",
    23: "Sees someone from their village",
    24: "Growth event",
    25: "Learns a new language",
    26: "Makes a great friend",
    27: "Falls madly in love",
    28: "Wins a TTRPG prize",
    29: "Upgrades their tools",
    30: "Gains a vehicle or horse",
    31: "An unforgettable festival",
    32: "Regrets an act",
    33: "Has offspring: a child",
    34: "Another passion",
    35: "Goes on a magical trip",
    36: "Writes a novel or short story",
    37: "Changes their life philosophy",
    38: "Returns to their village for a week",
    39: "Teaches a masterclass",
    40: "Works for someone famous",
    41: "Accepts a disciple",
    42: "Gets a small home",
    43: "Faces a faction against their art",
    44: "Roleplaying is in fashion!",
    45: "Lives a dangerous adventure",
    46: "Learns a new talent",
    47: "No patron: 1d6+1 years",
    48: "Inherits some assets",
    49: "An RPG makes him earn a lot",
    50: "Crisis: they question everything",
    51: "Deepening his art",
    52: "The role-playing union is created",
    53: "They join the artists' guild",
    54: "Suffers a family loss",
    55: "A pet joins",
    56: "The same dream repeats itself",
    57: "They need surgery and are cured",
    58: "Dangerous years of war",
    59: "Change in their personality",
    60: "Their magical GIFT intensifies!",
    61: "They could lose their enthusiasm",
    62: "The world is evolving a lot!",
    63: "They become a grandparent",
    64: "Meets an impossible love",
    65: "Learns to cast spells",
    66: "In prison for creating a roleplay",
    67: "Seriously considers leaving",
    68: "A nostalgic and melancholic year",
    69: "Reunites with a relative",
    70: "A former patron dies",
    71: "Experiences an emotional birthday",
    72: "Evades the clutches of death",
    73: "Is rewarded for their great work",
    74: "Needs to rest for a while",
    75: "Visits a loved one",
    76: "A monster accompanies them",
    77: "Almost no one remembers the RPGs",
    78: "They no longer understand the world",
    79: "Hope: a new apprentice",
    80: "They have no more strength left"
  },
  pl: {
    17: "Ma złamane serce",
    18: "Studiuje sztuki piękne",
    19: "Zyskuje zwierzęcego towarzysza",
    20: "Uczy się nowego talentu",
    21: "Przeżywa wielką przygodę",
    22: "Pracuje w innych zawodach",
    23: "Widzi kogoś ze swojej wioski",
    24: "Wydarzenie rozwojowe",
    25: "Uczy się nowego języka",
    26: "Zyskuje wspaniałego przyjaciela",
    27: "Szaleńczo się zakochuje",
    28: "Wygrywa nagrodę TTRPG",
    29: "Ulepsza swoje narzędzia",
    30: "Zdobywa pojazd albo konia",
    31: "Niezapomniany festiwal",
    32: "Żałuje pewnego czynu",
    33: "Ma potomstwo: dziecko",
    34: "Kolejna pasja",
    35: "Wyrusza w magiczną podróż",
    36: "Pisze powieść albo opowiadanie",
    37: "Zmienia swoją filozofię życia",
    38: "Wraca do swojej wioski na tydzień",
    39: "Prowadzi mistrzowskie zajęcia",
    40: "Pracuje dla kogoś sławnego",
    41: "Przyjmuje ucznia",
    42: "Dostaje niewielki dom",
    43: "Staje wobec frakcji przeciwnej swojej sztuce",
    44: "RPG-i są w modzie!",
    45: "Przeżywa niebezpieczną przygodę",
    46: "Uczy się nowego talentu",
    47: "Bez patrona: 1D6+1 lat",
    48: "Dziedziczy część majątku",
    49: "Pewne RPG przynosi spory zarobek",
    50: "Kryzys: kwestionuje wszystko",
    51: "Pogłębia swoją sztukę",
    52: "Powstaje związek twórców RPG",
    53: "Dołącza do gildii artystów",
    54: "Doświadcza straty w rodzinie",
    55: "Dołącza zwierzęcy towarzysz",
    56: "Ten sam sen powtarza się raz po raz",
    57: "Potrzebna jest operacja, ale kończy się wyzdrowieniem",
    58: "Niebezpieczne lata wojny",
    59: "Zmiana w osobowości",
    60: "Magiczny DAR staje się silniejszy!",
    61: "Mógłby stracić swój entuzjazm",
    62: "Świat bardzo się zmienia!",
    63: "Zostaje dziadkiem albo babcią",
    64: "Spotyka niemożliwą miłość",
    65: "Uczy się rzucać zaklęcia",
    66: "Trafia do więzienia za stworzenie gry fabularnej",
    67: "Poważnie rozważa odejście",
    68: "Rok nostalgii i melancholii",
    69: "Ponownie spotyka się z krewnym",
    70: "Umiera dawny patron",
    71: "Przeżywa emocjonalne urodziny",
    72: "Uchyla się szponom śmierci",
    73: "Otrzymuje nagrodę za swoją wielką pracę",
    74: "Potrzebuje przez jakiś czas odpocząć",
    75: "Odwiedza ukochaną osobę",
    76: "Zyskuje towarzystwo potwora",
    77: "Prawie nikt nie pamięta już RPG-ów",
    78: "Nie rozumie już świata",
    79: "Nadzieja: nowy uczeń",
    80: "Nie ma już w sobie sił"
  }
};

TABLES.adjectives = {
  label: { en: "600 ADJECTIVES", pl: "600 PRZYMIOTNIKÓW" },
  type: "adjective",
  en: {
    100: "strong", 101: "fragile", 102: "solid", 103: "liquid", 104: "gaseous",
    105: "dull", 106: "scratched", 107: "restored", 108: "repaired", 109: "desired",
    110: "repudiated", 111: "bright", 112: "dark", 113: "rare", 114: "unique",
    115: "common", 116: "natural", 117: "altered", 118: "beautiful", 119: "gorgeous",
    120: "ugly", 121: "hideous", 122: "useful", 123: "used", 124: "worn",
    125: "new", 126: "improved", 127: "clumsy", 128: "brave", 129: "avant-garde",
    130: "modern", 131: "ancient", 132: "unknown", 133: "broken", 134: "cracked",
    135: "charismatic", 136: "ornate", 137: "ostentatious", 138: "tacky", 139: "edible",
    140: "dangerous", 141: "sharp", 142: "throwable", 143: "pompous", 144: "careful",
    145: "careless", 146: "dilapidated", 147: "easy", 148: "difficult", 149: "complex",
    150: "useless", 151: "intuitive", 152: "so-so", 153: "valuable", 154: "insignificant",
    155: "military", 156: "transparent", 157: "opaque", 158: "furious", 159: "calm",
    160: "magical", 161: "anecdotal", 162: "mysterious", 163: "legendary", 164: "rough",
    165: "decorative", 166: "heavy", 167: "light", 168: "long", 169: "short",
    170: "round", 171: "square", 172: "soft", 173: "hard", 174: "smooth",
    175: "soothing", 176: "comfortable", 177: "pleasant", 178: "powerful", 179: "rigid",
    180: "flexible", 181: "famous", 182: "attractive", 183: "repellent", 184: "perfumed",
    185: "smelly", 186: "showy", 187: "tasty", 188: "sour", 189: "bitter",
    190: "sweet", 191: "salty", 192: "sad", 193: "alive", 194: "cheerful",
    195: "grayish", 196: "tidy", 197: "messy", 198: "dusty", 199: "clean",
    200: "dirty", 201: "shiny", 202: "stained", 203: "esoteric", 204: "shabby",
    205: "cheesy", 206: "spicy", 207: "overrated", 208: "underrated", 209: "luxurious",
    210: "tiny", 211: "enormous", 212: "lucid", 213: "traditional", 214: "cryptic",
    215: "energetic", 216: "friendly", 217: "treacherous", 218: "discreet", 219: "anodyne",
    220: "funny", 221: "somber", 222: "disturbing", 223: "rude", 224: "religious",
    225: "joyful", 226: "familiar", 227: "protective", 228: "swift", 229: "leisurely",
    230: "hot", 231: "cold", 232: "electric", 233: "busy", 234: "fluid",
    235: "high", 236: "low", 237: "dramatic", 238: "young", 239: "burnt",
    240: "florid", 241: "waning", 242: "waxing", 243: "diverse", 244: "monotonous",
    245: "basic", 246: "baroque", 247: "minimalist", 248: "harmful", 249: "healing",
    250: "exquisite", 251: "poor", 252: "tempting", 253: "ignored", 254: "marginalized",
    255: "impressive", 256: "stylish", 257: "close", 258: "distant", 259: "rusty",
    260: "supernatural", 261: "vague", 262: "concise", 263: "historic", 264: "casual",
    265: "sought-after", 266: "official", 267: "unusual", 268: "beneficial", 269: "unfavorable",
    270: "sick", 271: "healthy", 272: "neutral", 273: "habitual", 274: "routine",
    275: "organic", 276: "metallic", 277: "artificial", 278: "precious", 279: "mediocre",
    280: "pretty", 281: "noisy", 282: "masterful", 283: "elegant", 284: "sinuous",
    285: "solitary", 286: "numerous", 287: "gloomy", 288: "fine", 289: "thick",
    290: "thin", 291: "voluminous", 292: "vaporous", 293: "slight", 294: "stuffy",
    295: "lukewarm", 296: "sparkling", 297: "miraculous", 298: "hopeful", 299: "lifeless",
    300: "shocking", 301: "volatile", 302: "stable", 303: "constant", 304: "labyrinthine",
    305: "cutting", 306: "free", 307: "multiple", 308: "generous", 309: "sparse",
    310: "extravagant", 311: "cloudy", 312: "inspiring", 313: "bustling", 314: "serene",
    315: "expected", 316: "unexpected", 317: "rotten", 318: "corrupt", 319: "preserved",
    320: "straight", 321: "bent", 322: "crooked", 323: "firm", 324: "symbolic",
    325: "signaled", 326: "normative", 327: "colorful", 328: "functional", 329: "emotional",
    330: "thrilling", 331: "vibrant", 332: "crazy", 333: "irrational", 334: "logical",
    335: "resilient", 336: "alarming", 337: "elusive", 338: "artistic", 339: "artisan",
    340: "robust", 341: "rustic", 342: "rural", 343: "country", 344: "coarse",
    345: "exemplary", 346: "crude", 347: "delicate", 348: "appreciated", 349: "red",
    350: "vivid", 351: "dead", 352: "spectral", 353: "agile", 354: "incredible",
    355: "unprecedented", 356: "informative", 357: "wasted", 358: "prejudiced", 359: "kind",
    360: "little", 361: "indecorous", 362: "sordid", 363: "illusory", 364: "frustrating",
    365: "ordinary", 366: "disappointing", 367: "cynical", 368: "quantum", 369: "uniform",
    370: "prickly", 371: "dignified", 372: "slippery", 373: "secret", 374: "crunchy",
    375: "addictive", 376: "accomplished", 377: "long-lived", 378: "old", 379: "monstrous",
    380: "graceful", 381: "permitted", 382: "forbidden", 383: "physical", 384: "ethereal",
    385: "foreign", 386: "native", 387: "moribund", 388: "hampered", 389: "trapped",
    390: "fragmented", 391: "complete", 392: "distinct", 393: "peculiar", 394: "other",
    395: "similar", 396: "akin", 397: "wild", 398: "creepy", 399: "sinister",
    400: "comforting", 401: "compact", 402: "stupendous", 403: "detailed", 404: "bland",
    405: "mundane", 406: "scientific", 407: "mystic", 408: "spiritual", 409: "practical",
    410: "murky", 411: "flaky", 412: "charming", 413: "forceful", 414: "offensive",
    415: "peaceful", 416: "decorous", 417: "prolific", 418: "poetic", 419: "dreamlike",
    420: "professional", 421: "unfinished", 422: "perfect", 423: "imperfect", 424: "tangled",
    425: "confusing", 426: "harmonious", 427: "chaotic", 428: "honest", 429: "restorative",
    430: "toxic", 431: "expensive", 432: "cheap", 433: "null", 434: "meager",
    435: "banal", 436: "trivial", 437: "important", 438: "valid", 439: "serious",
    440: "acute", 441: "relevant", 442: "abundant", 443: "brief", 444: "extensive",
    445: "intense", 446: "sonorous", 447: "whispering", 448: "hissing", 449: "flat",
    450: "rugged", 451: "singular", 452: "mutated", 453: "exhausting", 454: "maddening",
    455: "exciting", 456: "tiring", 457: "relaxing", 458: "hazardous", 459: "eminent",
    460: "acceptable", 461: "productive", 462: "cultured", 463: "small", 464: "special",
    465: "large", 466: "amazing", 467: "swampy", 468: "surprising", 469: "abrupt",
    470: "hypnotic", 471: "believable", 472: "disheartening", 473: "masculine", 474: "feminine",
    475: "glamorous", 476: "negative", 477: "positive", 478: "present", 479: "nurturing",
    480: "fierce", 481: "resonant", 482: "icy", 483: "warm", 484: "tempered",
    485: "innate", 486: "damaged", 487: "conformist", 488: "silky", 489: "subtle",
    490: "pleasing", 491: "wrinkled", 492: "unwrinkled", 493: "conventional", 494: "original",
    495: "mythical", 496: "hardened", 497: "opposite", 498: "contrary", 499: "liminal",
    500: "aggressive", 501: "violent", 502: "bellicose", 503: "combative", 504: "provocative",
    505: "submissive", 506: "meek", 507: "intelligent", 508: "foolish", 509: "adaptable",
    510: "silent", 511: "stealthy", 512: "malicious", 513: "affable", 514: "affectionate",
    515: "mixed", 516: "reasonable", 517: "selective", 518: "tasteless", 519: "instinctive",
    520: "prehistoric", 521: "futuristic", 522: "hidden", 523: "sensory", 524: "sensitive",
    525: "sensible", 526: "vegetal", 527: "animal", 528: "exceptional", 529: "brown",
    530: "green", 531: "confused", 532: "touched", 533: "sunken", 534: "nailed",
    535: "limited", 536: "arduous", 537: "thorny", 538: "rancid", 539: "crystalline",
    540: "moldy", 541: "greenish", 542: "fabricated", 543: "dreamy", 544: "nightmarish",
    545: "terrible", 546: "innocent", 547: "hostile", 548: "substantial", 549: "flirtatious",
    550: "chrome", 551: "unsettling", 552: "concrete", 553: "invincible", 554: "invisible",
    555: "hallucinatory", 556: "fearful", 557: "sufficient", 558: "suspenseful", 559: "continuous",
    560: "captivating", 561: "qualitative", 562: "ritual", 563: "deceitful", 564: "jumbled",
    565: "diffuse", 566: "boring", 567: "enjoyable", 568: "absorbing", 569: "minimal",
    570: "massive", 571: "intricate", 572: "far", 573: "slack", 574: "experienced",
    575: "distended", 576: "inaccessible", 577: "accessible", 578: "impossible", 579: "bizarre",
    580: "wandering", 581: "tender", 582: "open", 583: "closed", 584: "blocked",
    585: "luminous", 586: "ghostly", 587: "dubious", 588: "flashy", 589: "deceptive",
    590: "white", 591: "black", 592: "bleeding", 593: "gentle", 594: "contemporary",
    595: "enraged", 596: "crushed", 597: "whole", 598: "empty", 599: "vacuous",
    600: "full", 601: "plenty", 602: "robotic", 603: "sophisticated", 604: "elaborate",
    605: "austere", 606: "efficient", 607: "suffocating", 608: "lucky", 609: "unlucky",
    610: "miserable", 611: "loose", 612: "bound", 613: "tied", 614: "exotic",
    615: "eccentric", 616: "weak", 617: "animate", 618: "absurd", 619: "varied",
    620: "dry", 621: "wet", 622: "unusable", 623: "superficial", 624: "superfluous",
    625: "unpredictable", 626: "indispensable", 627: "puerile", 628: "usable", 629: "optimal",
    630: "fertile", 631: "lousy", 632: "rooted", 633: "skillful", 634: "dexterous",
    635: "wise", 636: "genuine", 637: "popular", 638: "still", 639: "talkative",
    640: "insulting", 641: "mental", 642: "bodily", 643: "psychic", 644: "paradoxical",
    645: "metaphorical", 646: "sarcastic", 647: "masked", 648: "ironic", 649: "exaggerated",
    650: "abstract", 651: "ideal", 652: "indefinite", 653: "undulating", 654: "groundbreaking",
    655: "legitimate", 656: "reminiscent", 657: "evocative", 658: "worsened", 659: "improvable",
    660: "uncountable", 661: "vast", 662: "reserved", 663: "blinding", 664: "fascinating",
    665: "magnetic", 666: "hungry", 667: "thirsty", 668: "tired", 669: "tiresome",
    670: "crafty", 671: "restrained", 672: "rhythmic", 673: "asynchronous", 674: "fearsome",
    675: "fractured", 676: "pious", 677: "malevolent", 678: "immaculate", 679: "crowded",
    680: "steep", 681: "automatic", 682: "rhetorical", 683: "challenging", 684: "naive",
    685: "simple", 686: "agonizing", 687: "illustrious", 688: "psychedelic", 689: "childish",
    690: "adult", 691: "mature", 692: "immature", 693: "mischievous", 694: "pure",
    695: "impure", 696: "neat", 697: "slender", 698: "plump", 699: "atypical"
  },
  pl: {
    100: "silny", 101: "kruchy", 102: "solidny", 103: "ciekły", 104: "gazowy",
    105: "tępy", 106: "porysowany", 107: "odrestaurowany", 108: "naprawiony", 109: "pożądany",
    110: "odrzucony", 111: "jasny", 112: "ciemny", 113: "rzadki", 114: "unikalny",
    115: "pospolity", 116: "naturalny", 117: "zmieniony", 118: "piękny", 119: "olśniewający",
    120: "brzydki", 121: "ohydny", 122: "użyteczny", 123: "używany", 124: "zużyty",
    125: "nowy", 126: "ulepszony", 127: "niezdarny", 128: "odważny", 129: "awangardowy",
    130: "nowoczesny", 131: "starożytny", 132: "nieznany", 133: "zepsuty", 134: "popękany",
    135: "charyzmatyczny", 136: "ozdobny", 137: "ostentacyjny", 138: "tandetny", 139: "jadalny",
    140: "niebezpieczny", 141: "ostry", 142: "nadający się do rzucania", 143: "pompatyczny", 144: "ostrożny",
    145: "nieostrożny", 146: "zrujnowany", 147: "łatwy", 148: "trudny", 149: "złożony",
    150: "bezużyteczny", 151: "intuicyjny", 152: "taki sobie", 153: "wartościowy", 154: "nieistotny",
    155: "wojskowy", 156: "przezroczysty", 157: "nieprzezroczysty", 158: "wściekły", 159: "spokojny",
    160: "magiczny", 161: "anegdotyczny", 162: "tajemniczy", 163: "legendarny", 164: "chropowaty",
    165: "dekoracyjny", 166: "ciężki", 167: "lekki", 168: "długi", 169: "krótki",
    170: "okrągły", 171: "kwadratowy", 172: "miękki", 173: "twardy", 174: "gładki",
    175: "kojący", 176: "wygodny", 177: "przyjemny", 178: "potężny", 179: "sztywny",
    180: "elastyczny", 181: "sławny", 182: "atrakcyjny", 183: "odpychający", 184: "pachnący",
    185: "śmierdzący", 186: "krzykliwy", 187: "smaczny", 188: "kwaśny", 189: "gorzki",
    190: "słodki", 191: "słony", 192: "smutny", 193: "żywy", 194: "pogodny",
    195: "szarawy", 196: "schludny", 197: "bałaganiarski", 198: "zakurzony", 199: "czysty",
    200: "brudny", 201: "lśniący", 202: "poplamiony", 203: "ezoteryczny", 204: "podniszczony",
    205: "kiczowaty", 206: "pikantny", 207: "przeceniany", 208: "niedoceniany", 209: "luksusowy",
    210: "maleńki", 211: "ogromny", 212: "klarowny", 213: "tradycyjny", 214: "zagadkowy",
    215: "energiczny", 216: "przyjazny", 217: "zdradliwy", 218: "dyskretny", 219: "nijaki",
    220: "zabawny", 221: "posępny", 222: "niepokojący", 223: "niegrzeczny", 224: "religijny",
    225: "radosny", 226: "znajomy", 227: "opiekuńczy", 228: "szybki", 229: "niespieszny",
    230: "gorący", 231: "zimny", 232: "elektryczny", 233: "zajęty", 234: "płynny",
    235: "wysoki", 236: "niski", 237: "dramatyczny", 238: "młody", 239: "spalony",
    240: "kwiecisty", 241: "malejący", 242: "rosnący", 243: "różnorodny", 244: "monotonny",
    245: "podstawowy", 246: "barokowy", 247: "minimalistyczny", 248: "szkodliwy", 249: "uzdrawiający",
    250: "wykwintny", 251: "biedny", 252: "kuszący", 253: "ignorowany", 254: "marginalizowany",
    255: "imponujący", 256: "stylowy", 257: "bliski", 258: "odległy", 259: "zardzewiały",
    260: "nadprzyrodzony", 261: "mglisty", 262: "zwięzły", 263: "historyczny", 264: "swobodny",
    265: "pożądany", 266: "oficjalny", 267: "niezwykły", 268: "korzystny", 269: "niekorzystny",
    270: "chory", 271: "zdrowy", 272: "neutralny", 273: "nawykowy", 274: "rutynowy",
    275: "organiczny", 276: "metaliczny", 277: "sztuczny", 278: "cenny", 279: "przeciętny",
    280: "ładny", 281: "hałaśliwy", 282: "mistrzowski", 283: "elegancki", 284: "falisty",
    285: "samotny", 286: "liczny", 287: "ponury", 288: "subtelny", 289: "gruby",
    290: "cienki", 291: "obszerny", 292: "parowy", 293: "lekki", 294: "duszny",
    295: "letni", 296: "iskrzący", 297: "cudowny", 298: "pełen nadziei", 299: "bez życia",
    300: "szokujący", 301: "niestabilny", 302: "stabilny", 303: "stały", 304: "labiryntowy",
    305: "tnący", 306: "wolny", 307: "wieloraki", 308: "hojny", 309: "rzadki",
    310: "ekstrawagancki", 311: "pochmurny", 312: "inspirujący", 313: "tętniący życiem", 314: "pogodny",
    315: "spodziewany", 316: "niespodziewany", 317: "zgniły", 318: "zepsuty", 319: "zachowany",
    320: "prosty", 321: "zgięty", 322: "krzywy", 323: "zwarty", 324: "symboliczny",
    325: "zasygnalizowany", 326: "normatywny", 327: "kolorowy", 328: "funkcjonalny", 329: "emocjonalny",
    330: "ekscytujący", 331: "żywiołowy", 332: "szalony", 333: "irracjonalny", 334: "logiczny",
    335: "odporny", 336: "alarmujący", 337: "nieuchwytny", 338: "artystyczny", 339: "rzemieślniczy",
    340: "solidny", 341: "rustykalny", 342: "wiejski", 343: "prowincjonalny", 344: "szorstki",
    345: "wzorcowy", 346: "prymitywny", 347: "delikatny", 348: "doceniony", 349: "czerwony",
    350: "jaskrawy", 351: "martwy", 352: "widmowy", 353: "zwinny", 354: "niesamowity",
    355: "bezprecedensowy", 356: "informacyjny", 357: "zmarnowany", 358: "uprzedzony", 359: "miły",
    360: "mały", 361: "nieprzyzwoity", 362: "podły", 363: "iluzoryczny", 364: "frustrujący",
    365: "zwyczajny", 366: "rozczarowujący", 367: "cyniczny", 368: "kwantowy", 369: "jednolity",
    370: "kłujący", 371: "dostojny", 372: "śliski", 373: "sekretny", 374: "chrupiący",
    375: "uzależniający", 376: "dokonany", 377: "długowieczny", 378: "stary", 379: "monstrualny",
    380: "pełen gracji", 381: "dozwolony", 382: "zakazany", 383: "fizyczny", 384: "eteryczny",
    385: "obcy", 386: "rodzimy", 387: "dogorywający", 388: "utrudniony", 389: "uwięziony",
    390: "pofragmentowany", 391: "kompletny", 392: "wyraźny", 393: "osobliwy", 394: "inny",
    395: "podobny", 396: "pokrewny", 397: "dziki", 398: "upiorny", 399: "złowieszczy",
    400: "pokrzepiający", 401: "zwarty", 402: "zdumiewający", 403: "szczegółowy", 404: "mdły",
    405: "przyziemny", 406: "naukowy", 407: "mistyczny", 408: "duchowy", 409: "praktyczny",
    410: "mętny", 411: "łuszczący się", 412: "czarujący", 413: "stanowczy", 414: "obraźliwy",
    415: "pokojowy", 416: "stateczny", 417: "płodny", 418: "poetycki", 419: "oniryczny",
    420: "profesjonalny", 421: "niedokończony", 422: "perfekcyjny", 423: "niedoskonały", 424: "splątany",
    425: "mylący", 426: "harmonijny", 427: "chaotyczny", 428: "szczery", 429: "regenerujący",
    430: "toksyczny", 431: "drogi", 432: "tani", 433: "zerowy", 434: "mizerny",
    435: "banalny", 436: "błahy", 437: "ważny", 438: "ważny", 439: "poważny",
    440: "ostry", 441: "istotny", 442: "obfity", 443: "krótki", 444: "rozległy",
    445: "intensywny", 446: "dźwięczny", 447: "szepczący", 448: "syczący", 449: "płaski",
    450: "surowy", 451: "pojedynczy", 452: "zmutowany", 453: "wyczerpujący", 454: "doprowadzający do szału",
    455: "ekscytujący", 456: "męczący", 457: "relaksujący", 458: "niebezpieczny", 459: "wybitny",
    460: "akceptowalny", 461: "produktywny", 462: "kulturalny", 463: "mały", 464: "szczególny",
    465: "wielki", 466: "zdumiewający", 467: "bagnisty", 468: "zaskakujący", 469: "nagły",
    470: "hipnotyczny", 471: "wiarygodny", 472: "przygnębiający", 473: "męski", 474: "kobiecy",
    475: "olśniewający", 476: "negatywny", 477: "pozytywny", 478: "obecny", 479: "opiekuńczy",
    480: "zaciekły", 481: "rezonujący", 482: "lodowaty", 483: "ciepły", 484: "stonowany",
    485: "wrodzony", 486: "uszkodzony", 487: "konformistyczny", 488: "jedwabisty", 489: "subtelny",
    490: "przyjemny", 491: "pomarszczony", 492: "gładki", 493: "konwencjonalny", 494: "oryginalny",
    495: "mityczny", 496: "zahartowany", 497: "przeciwny", 498: "odwrotny", 499: "liminalny",
    500: "agresywny", 501: "brutalny", 502: "wojowniczy", 503: "bojowy", 504: "prowokacyjny",
    505: "uległy", 506: "potulny", 507: "inteligentny", 508: "głupi", 509: "adaptowalny",
    510: "cichy", 511: "skryty", 512: "złośliwy", 513: "uprzejmy", 514: "czuły",
    515: "mieszany", 516: "rozsądny", 517: "selektywny", 518: "bez smaku", 519: "instynktowny",
    520: "prehistoryczny", 521: "futurystyczny", 522: "ukryty", 523: "zmysłowy", 524: "wrażliwy",
    525: "rozsądny", 526: "roślinny", 527: "zwierzęcy", 528: "wyjątkowy", 529: "brązowy",
    530: "zielony", 531: "zagubiony", 532: "poruszony", 533: "zatopiony", 534: "przybity gwoździami",
    535: "ograniczony", 536: "żmudny", 537: "ciernisty", 538: "zjełczały", 539: "krystaliczny",
    540: "spleśniały", 541: "zielonkawy", 542: "sfabrykowany", 543: "senny", 544: "koszmarny",
    545: "straszny", 546: "niewinny", 547: "wrogi", 548: "znaczący", 549: "flirtujący",
    550: "chromowany", 551: "niepokojący", 552: "betonowy", 553: "niezwyciężony", 554: "niewidzialny",
    555: "halucynacyjny", 556: "pełen lęku", 557: "wystarczający", 558: "pełen napięcia", 559: "ciągły",
    560: "urzekający", 561: "jakościowy", 562: "rytualny", 563: "zwodniczy", 564: "pomieszany",
    565: "rozproszony", 566: "nudny", 567: "przyjemny", 568: "pochłaniający", 569: "minimalny",
    570: "masywny", 571: "misterny", 572: "daleki", 573: "luźny", 574: "doświadczony",
    575: "rozdęty", 576: "niedostępny", 577: "dostępny", 578: "niemożliwy", 579: "dziwaczny",
    580: "błądzący", 581: "delikatny", 582: "otwarty", 583: "zamknięty", 584: "zablokowany",
    585: "świetlisty", 586: "upiorny", 587: "wątpliwy", 588: "krzykliwy", 589: "zwodniczy",
    590: "biały", 591: "czarny", 592: "krwawiący", 593: "łagodny", 594: "współczesny",
    595: "rozwścieczony", 596: "zmiażdżony", 597: "cały", 598: "pusty", 599: "próżny",
    600: "pełny", 601: "obfity", 602: "robotyczny", 603: "wyrafinowany", 604: "rozbudowany",
    605: "surowy", 606: "wydajny", 607: "duszący", 608: "szczęśliwy", 609: "pechowy",
    610: "nieszczęsny", 611: "luźny", 612: "związany", 613: "powiązany", 614: "egzotyczny",
    615: "ekscentryczny", 616: "słaby", 617: "ożywiony", 618: "absurdalny", 619: "zróżnicowany",
    620: "suchy", 621: "mokry", 622: "nienadający się do użytku", 623: "powierzchowny", 624: "zbędny",
    625: "nieprzewidywalny", 626: "niezbędny", 627: "dziecinny", 628: "używalny", 629: "optymalny",
    630: "żyzny", 631: "kiepski", 632: "zakorzeniony", 633: "zręczny", 634: "sprawny",
    635: "mądry", 636: "autentyczny", 637: "popularny", 638: "nieruchomy", 639: "rozmowny",
    640: "obraźliwy", 641: "mentalny", 642: "cielesny", 643: "psychiczny", 644: "paradoksalny",
    645: "metaforyczny", 646: "sarkastyczny", 647: "zamaskowany", 648: "ironiczny", 649: "przesadzony",
    650: "abstrakcyjny", 651: "idealny", 652: "nieokreślony", 653: "falujący", 654: "przełomowy",
    655: "uzasadniony", 656: "przywołujący wspomnienia", 657: "sugestywny", 658: "pogorszony", 659: "możliwy do poprawy",
    660: "niezliczony", 661: "rozległy", 662: "powściągliwy", 663: "oślepiający", 664: "fascynujący",
    665: "magnetyczny", 666: "głodny", 667: "spragniony", 668: "zmęczony", 669: "męczący",
    670: "przebiegły", 671: "powściągnięty", 672: "rytmiczny", 673: "asynchroniczny", 674: "budzący grozę",
    675: "pęknięty", 676: "pobożny", 677: "złowrogi", 678: "nieskalany", 679: "zatłoczony",
    680: "stromy", 681: "automatyczny", 682: "retoryczny", 683: "wymagający", 684: "naiwny",
    685: "prosty", 686: "bolesny", 687: "znakomity", 688: "psychodeliczny", 689: "dziecięcy",
    690: "dorosły", 691: "dojrzały", 692: "niedojrzały", 693: "psotny", 694: "czysty",
    695: "nieczysty", 696: "schludny", 697: "smukły", 698: "pulchny", 699: "nietypowy"
  }
};
